$primary = rgb(1e66f5)
$surface = rgb(eff1f5)
$secondary = rgb(7287fd)
$error = rgb(d20f39)
$tertiary = rgb(8839ef)
$surface_lowest = rgb(e8eaef)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
