# ============================================================
#  ~/.config/hypr/hyprland.conf
#  ENTRY POINT — sources all modular config files
# ============================================================

# Load environment variables FIRST — before anything else
source = ~/.config/hypr/env.conf

# Core compositor behavior
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/layouts.conf


# Keybinds and workspace rules
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/workspaces.conf

# Autostart — Noctalia and essential services launch here
source = ~/.config/hypr/autostart.conf

source = /home/naeem/.config/hypr/noctalia/noctalia-colors.conf

