general {
    lock_cmd = qs -c noctalia-shell ipc call lockScreen lock  # Noctalia lock command
    before_sleep_cmd = qs -c noctalia-shell ipc call lockScreen lock  # Lock before sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screens on after wake
}

# Lock screen after 10 minutes (600 seconds)
listener {
    timeout = 600
    on-timeout = qs -c noctalia-shell ipc call lockScreen lock
}

# Turn off displays after 30 minutes (1800 seconds)
listener {
#    timeout = 1800
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
