# See https://wiki.hyprland.org/Configuring/Monitors/
# ============================================================
#  ~/.config/hypr/monitor.conf
#  Monitor / display setup
#
#  Format: monitor = NAME, RESOLUTION@REFRESH, POSITION, SCALE
#
#  To find your monitor name, run: hyprctl monitors
#  Common names: eDP-1 (laptop), HDMI-A-1, DP-1, DP-2
# ============================================================
monitorv2 {
    output = HDMI-A-1
    mode = 3440x1440@100.00Hz
    position = 0x0
    scale = 1
    supports_hdr = true
    supports_wide_color = true
    vrr = 1  # Adaptive sync - helps with frame pacing
}

monitorv2 {
    output = eDP-1
    mode = 1920x1200@60.03Hz
    position = 3440x0 #enable it for Office laptop
    scale = 1.50
    supports_hdr = true
    supports_wide_color = true
    vrr = 1
}

#monitorv2 {
#    output = DP-3
#    mode = 3440x1440@59.97Hz
#    position = 0x0 #enable it for Office laptop
#    scale = 1.00
#    supports_hdr = true
#    supports_wide_color = true
#    vrr = 1
#}
