return {
  'RRethy/base16-nvim',
  priority = 1000,
  config = function()
    -- Italic comments. matugen.lua is regenerated by Noctalia, so wrap
    -- base16's setup instead; this also survives matugen's SIGUSR1 reloads
    -- (they re-require matugen, not base16-colorscheme). Treesitter's
    -- @comment is already italic in base16; this covers plain Comment.
    local b16 = require('base16-colorscheme')
    local setup = b16.setup
    b16.setup = function(...)
      setup(...)
      vim.api.nvim_set_hl(0, 'Comment', { fg = b16.colors.base03, italic = true })
    end

    local ok, matugen = pcall(require, 'matugen')
    if ok then matugen.setup() end
  end,
}
