-- Colours come from Noctalia, not from a colorscheme plugin. Noctalia's nvim
-- template renders lua/matugen.lua with a base16 palette for the active scheme
-- (Gruvbox, light or dark per its Auto theme mode) and sends SIGUSR1 on every re-render, which
-- matugen.lua catches to re-apply itself. So changing the Noctalia scheme
-- re-themes running editors too; never hand-edit matugen.lua.
return {
  {
    "RRethy/base16-nvim",
    lazy = false,
    priority = 1000,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = function()
        -- matugen.lua is regenerated by Noctalia, so wrap base16's setup
        -- instead of editing it; the wrapper also runs on matugen's SIGUSR1
        -- reloads (they re-require matugen, not base16-colorscheme).
        local b16 = require("base16-colorscheme")
        local setup = b16.setup
        b16.setup = function(colors, ...)
          -- base16-nvim does not set 'background' itself, and plugins that
          -- pick light/dark variants of their own highlights read it. Derive it
          -- from base00 so it follows Noctalia's Auto theme mode. colors_name is
          -- cleared first, since changing 'background' with it set re-runs
          -- :colorscheme on that name.
          local hex = type(colors) == "table" and colors.base00
          if hex then
            local r, g, b = tonumber(hex:sub(2, 3), 16), tonumber(hex:sub(4, 5), 16), tonumber(hex:sub(6, 7), 16)
            local mode = (0.299 * r + 0.587 * g + 0.114 * b) < 128 and "dark" or "light"
            if vim.o.background ~= mode then
              vim.g.colors_name = nil
              vim.o.background = mode
            end
          end
          setup(colors, ...)
          -- Italic comments. Treesitter's @comment is already italic in
          -- base16; this covers plain Comment.
          vim.api.nvim_set_hl(0, "Comment", { fg = b16.colors.base03, italic = true })
        end

        require("matugen").setup()
      end,
    },
  },
}
